/**
 * Akura AI - Report Modal Component
 *
 * Child-friendly insights dashboard with fun visualizations.
 * Includes feedback data export for model fine-tuning.
 */

import React, { useState, useMemo } from "react";
import {
  X,
  BarChart3,
  TrendingUp,
  FileText,
  Download,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Database,
  Brain,
  Edit3,
  Trophy,
  Star,
  Sparkles,
  Award,
} from "lucide-react";
import { useAnalysis } from "../context/AnalysisContext";
import { Button, Badge } from "./ui";

function ReportModal() {
  const {
    toggleReport,
    totalErrors,
    correctedCount,
    ignoredCount,
    pendingCount,
    patternDistribution,
    originalText,
    getFinalText,
    processingTime,
    modelUsed,
    tokens,
    getFeedbackStats,
    exportFeedbackData,
    exportFeedbackJsonl,
  } = useAnalysis();

  // Get feedback statistics
  const feedbackStats = useMemo(() => getFeedbackStats(), [getFeedbackStats]);

  // Calculate pattern percentages
  const totalPatterns = Object.values(patternDistribution).reduce(
    (a, b) => a + b,
    0
  );
  const patternPercentages = Object.entries(patternDistribution).map(
    ([pattern, count]) => ({
      pattern,
      count,
      percentage:
        totalPatterns > 0 ? Math.round((count / totalPatterns) * 100) : 0,
      color: getPatternColor(pattern),
      emoji: getPatternEmoji(pattern),
    })
  );

  function getPatternColor(pattern) {
    const p = pattern.toLowerCase();
    if (p.includes("visual") || p.includes("scrambl")) return "#60a5fa"; // Blue
    if (p.includes("phonetic") || p.includes("dental")) return "#fbbf24"; // Amber
    if (p.includes("grammar") || p.includes("spoken")) return "#a78bfa"; // Purple
    return "#f87171"; // Red default
  }

  function getPatternEmoji(pattern) {
    const p = pattern.toLowerCase();
    if (p.includes("visual") || p.includes("scrambl")) return "👀";
    if (p.includes("phonetic") || p.includes("dental")) return "👂";
    if (p.includes("grammar") || p.includes("spoken")) return "💬";
    return "✏️";
  }

  // Get all errors for the table
  const errorTokens = tokens.filter((t) => t.type === "error");

  // Calculate score
  const score = totalErrors > 0 ? Math.round((correctedCount / totalErrors) * 100) : 0;

  // Export report as text
  const handleExport = () => {
    const report = `
AKURA AI - Dyslexia Analysis Report
=====================================
Date: ${new Date().toLocaleString()}
Model: ${modelUsed}
Processing Time: ${processingTime?.toFixed(0)}ms

ORIGINAL TEXT:
${originalText}

CORRECTED TEXT:
${getFinalText()}

STATISTICS:
- Total Errors: ${totalErrors}
- Corrected: ${correctedCount}
- Ignored: ${ignoredCount}
- Pending: ${pendingCount}

PATTERN DISTRIBUTION:
${patternPercentages
  .map((p) => `- ${p.pattern}: ${p.count} (${p.percentage}%)`)
  .join("\n")}

ERROR DETAILS:
${errorTokens
  .map(
    (e, i) =>
      `${i + 1}. "${e.originalWord}" → "${e.correctedWord}" [${e.pattern}]`
  )
  .join("\n")}

=====================================
Generated by Akura AI - Intelligent Dyslexia Correction Engine
    `.trim();

    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `akura-report-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
      <div className="w-full max-w-4xl max-h-[90vh] bg-white rounded-3xl shadow-2xl overflow-hidden flex flex-col border-2 border-primary-200">
        {/* Fun Header */}
        <div className="px-6 py-5 bg-gradient-to-r from-primary-500 via-primary-400 to-accent-yellow text-white flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="w-14 h-14 bg-white/20 rounded-2xl flex items-center justify-center">
              <Trophy className="w-8 h-8" />
            </div>
            <div>
              <h2 className="text-xl font-bold flex items-center gap-2">
                📊 Your Learning Report
                <Sparkles className="w-5 h-5 animate-pulse" />
              </h2>
              <p className="text-sm text-primary-100">
                See how well you did! 🌟
              </p>
            </div>
          </div>
          <button
            onClick={toggleReport}
            className="p-3 hover:bg-white/20 rounded-xl transition-colors"
          >
            <X className="w-6 h-6" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6 scrollbar-thin">
          {/* Score Banner */}
          <div className="mb-6 p-6 bg-gradient-to-r from-primary-100 via-primary-50 to-accent-yellow/20 rounded-2xl border-2 border-primary-200 text-center">
            <div className="flex items-center justify-center gap-3 mb-2">
              {score >= 80 ? (
                <Award className="w-10 h-10 text-accent-yellow" />
              ) : score >= 50 ? (
                <Star className="w-10 h-10 text-primary-500" />
              ) : (
                <TrendingUp className="w-10 h-10 text-primary-400" />
              )}
              <span className="text-5xl font-extrabold text-primary-700">{score}%</span>
            </div>
            <p className="text-lg font-bold text-primary-600">
              {score >= 80
                ? "🎉 Amazing Work! You're a Star!"
                : score >= 50
                ? "👍 Good Job! Keep Learning!"
                : "💪 Keep Trying! You Can Do It!"}
            </p>
          </div>

          {/* Stats Cards - Fun Design */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
            <div className="bg-gradient-to-br from-red-50 to-red-100 rounded-2xl p-5 text-center border-2 border-red-200 shadow-sm">
              <div className="w-12 h-12 bg-red-200 rounded-full flex items-center justify-center mx-auto mb-3">
                <AlertTriangle className="w-6 h-6 text-red-600" />
              </div>
              <p className="text-3xl font-extrabold text-red-600">{totalErrors}</p>
              <p className="text-sm text-red-500 font-bold">🔍 Found</p>
            </div>
            <div className="bg-gradient-to-br from-green-50 to-green-100 rounded-2xl p-5 text-center border-2 border-green-200 shadow-sm">
              <div className="w-12 h-12 bg-green-200 rounded-full flex items-center justify-center mx-auto mb-3">
                <CheckCircle2 className="w-6 h-6 text-green-600" />
              </div>
              <p className="text-3xl font-extrabold text-green-600">{correctedCount}</p>
              <p className="text-sm text-green-500 font-bold">✅ Fixed</p>
            </div>
            <div className="bg-gradient-to-br from-gray-50 to-gray-100 rounded-2xl p-5 text-center border-2 border-gray-200 shadow-sm">
              <div className="w-12 h-12 bg-gray-200 rounded-full flex items-center justify-center mx-auto mb-3">
                <XCircle className="w-6 h-6 text-gray-500" />
              </div>
              <p className="text-3xl font-extrabold text-gray-600">{ignoredCount}</p>
              <p className="text-sm text-gray-500 font-bold">⏭️ Skipped</p>
            </div>
            <div className="bg-gradient-to-br from-amber-50 to-amber-100 rounded-2xl p-5 text-center border-2 border-amber-200 shadow-sm">
              <div className="w-12 h-12 bg-amber-200 rounded-full flex items-center justify-center mx-auto mb-3">
                <TrendingUp className="w-6 h-6 text-amber-600" />
              </div>
              <p className="text-3xl font-extrabold text-amber-600">{score}%</p>
              <p className="text-sm text-amber-500 font-bold">📈 Score</p>
            </div>
          </div>

          {/* Pattern Distribution - Fun Bars */}
          <div className="mb-6 bg-gradient-to-br from-primary-50 to-white rounded-2xl p-5 border-2 border-primary-100">
            <h3 className="text-base font-bold text-primary-700 mb-4 flex items-center gap-2">
              <BarChart3 className="w-5 h-5" />
              🎯 What Types of Mistakes?
            </h3>
            <div className="space-y-4">
              {patternPercentages.map(
                ({ pattern, count, percentage, color, emoji }) => (
                  <div key={pattern}>
                    <div className="flex items-center justify-between text-sm mb-2">
                      <span className="font-bold text-gray-700 flex items-center gap-2">
                        <span className="text-xl">{emoji}</span>
                        {pattern}
                      </span>
                      <span
                        className="font-bold px-3 py-1 rounded-full text-white text-xs"
                        style={{ backgroundColor: color }}
                      >
                        {count} ({percentage}%)
                      </span>
                    </div>
                    <div className="h-4 bg-gray-100 rounded-full overflow-hidden">
                      <div
                        className="h-full rounded-full transition-all duration-700 ease-out"
                        style={{
                          width: `${percentage}%`,
                          backgroundColor: color,
                        }}
                      />
                    </div>
                  </div>
                )
              )}
            </div>
          </div>

          {/* Error Table - Simplified for Kids */}
          <div className="mb-6 bg-white rounded-2xl border-2 border-primary-100 overflow-hidden">
            <h3 className="text-base font-bold text-primary-700 p-4 bg-primary-50 flex items-center gap-2 border-b-2 border-primary-100">
              <FileText className="w-5 h-5" />
              📝 All the Changes
            </h3>
            <div className="max-h-48 overflow-y-auto">
              <table className="w-full text-sm">
                <thead className="bg-primary-50 sticky top-0">
                  <tr>
                    <th className="px-4 py-3 text-left text-primary-600 font-bold">
                      ❌ Before
                    </th>
                    <th className="px-4 py-3 text-left text-primary-600 font-bold">
                      ✅ After
                    </th>
                    <th className="px-4 py-3 text-left text-primary-600 font-bold">
                      📌 Status
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-primary-50">
                  {errorTokens.map((token) => (
                    <tr key={token.id} className="hover:bg-primary-50/50">
                      <td className="px-4 py-3 sinhala-text text-red-600 font-bold">
                        {token.originalWord}
                      </td>
                      <td className="px-4 py-3 sinhala-text text-green-600 font-bold">
                        {token.correctedWord}
                      </td>
                      <td className="px-4 py-3">
                        <span
                          className={`px-3 py-1 rounded-full text-xs font-bold ${
                            token.state === "corrected"
                              ? "bg-green-100 text-green-700"
                              : token.state === "ignored"
                              ? "bg-gray-100 text-gray-600"
                              : "bg-amber-100 text-amber-700"
                          }`}
                        >
                          {token.state === "corrected"
                            ? "✅ Fixed"
                            : token.state === "ignored"
                            ? "⏭️ Skipped"
                            : "⏳ Waiting"}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Text Comparison */}
          <div className="mb-6">
            <h3 className="text-base font-bold text-primary-700 mb-3 flex items-center gap-2">
              <FileText className="w-5 h-5" />
              📖 Before & After
            </h3>
            <div className="grid md:grid-cols-2 gap-4">
              <div className="p-5 bg-gradient-to-br from-red-50 to-red-100 rounded-2xl border-2 border-red-200">
                <p className="text-sm text-red-600 font-bold mb-2 flex items-center gap-1">
                  ❌ Original Writing
                </p>
                <p className="sinhala-text text-red-700 text-lg">{originalText}</p>
              </div>
              <div className="p-5 bg-gradient-to-br from-green-50 to-green-100 rounded-2xl border-2 border-green-200">
                <p className="text-sm text-green-600 font-bold mb-2 flex items-center gap-1">
                  ✅ Corrected Writing
                </p>
                <p className="sinhala-text text-green-700 text-lg">{getFinalText()}</p>
              </div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-4 bg-gradient-to-r from-primary-50 to-white border-t-2 border-primary-100 flex items-center justify-between">
          <div className="text-sm text-primary-500 font-medium">
            🤖 {modelUsed} • ⚡ {processingTime?.toFixed(0)}ms
          </div>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" onClick={handleExport}>
              <Download className="w-4 h-4" />
              📄 Get Report
            </Button>
            <Button variant="secondary" size="sm" onClick={exportFeedbackJsonl}>
              <Brain className="w-4 h-4" />
              🧠 Training Data
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}

export default ReportModal;
