/**
 * Akura AI - Report Modal Component
 * 
 * Insights dashboard showing pattern distribution and statistics.
 */

import React from 'react';
import { X, PieChart, TrendingUp, FileText, Download, CheckCircle2, XCircle, AlertTriangle } from 'lucide-react';
import { useAnalysis } from '../context/AnalysisContext';
import { PATTERN_COLORS } from '../constants';

function ReportModal() {
  const { 
    toggleReport, 
    totalErrors, 
    correctedCount, 
    ignoredCount,
    pendingCount,
    patternDistribution,
    originalText,
    getFinalText,
    processingTime,
    modelUsed,
    tokens,
  } = useAnalysis();
  
  // Calculate pattern percentages
  const totalPatterns = Object.values(patternDistribution).reduce((a, b) => a + b, 0);
  const patternPercentages = Object.entries(patternDistribution).map(([pattern, count]) => ({
    pattern,
    count,
    percentage: totalPatterns > 0 ? Math.round((count / totalPatterns) * 100) : 0,
    color: getPatternColor(pattern),
  }));
  
  function getPatternColor(pattern) {
    const p = pattern.toLowerCase();
    if (p.includes('visual') || p.includes('scrambl')) return '#3B82F6'; // Blue
    if (p.includes('phonetic') || p.includes('dental')) return '#F59E0B'; // Amber
    if (p.includes('grammar') || p.includes('spoken')) return '#8B5CF6'; // Purple
    return '#EF4444'; // Red default
  }
  
  // Get all errors for the table
  const errorTokens = tokens.filter(t => t.type === 'error');
  
  // Export report as text
  const handleExport = () => {
    const report = `
AKURA AI - Dyslexia Analysis Report
=====================================
Date: ${new Date().toLocaleString()}
Model: ${modelUsed}
Processing Time: ${processingTime?.toFixed(0)}ms

ORIGINAL TEXT:
${originalText}

CORRECTED TEXT:
${getFinalText()}

STATISTICS:
- Total Errors: ${totalErrors}
- Corrected: ${correctedCount}
- Ignored: ${ignoredCount}
- Pending: ${pendingCount}

PATTERN DISTRIBUTION:
${patternPercentages.map(p => `- ${p.pattern}: ${p.count} (${p.percentage}%)`).join('\n')}

ERROR DETAILS:
${errorTokens.map((e, i) => `${i + 1}. "${e.originalWord}" → "${e.correctedWord}" [${e.pattern}]`).join('\n')}

=====================================
Generated by Akura AI - Intelligent Dyslexia Correction Engine
    `.trim();
    
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `akura-report-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };
  
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm">
      <div className="w-full max-w-3xl max-h-[90vh] bg-white rounded-2xl shadow-2xl overflow-hidden flex flex-col m-4">
        {/* Header */}
        <div className="px-6 py-4 bg-gradient-to-r from-indigo-500 to-purple-600 text-white flex items-center justify-between">
          <div className="flex items-center gap-3">
            <PieChart className="w-6 h-6" />
            <div>
              <h2 className="text-lg font-semibold">Analysis Report</h2>
              <p className="text-xs text-indigo-100">Detailed insights and statistics</p>
            </div>
          </div>
          <button
            onClick={toggleReport}
            className="p-2 hover:bg-white/20 rounded-lg transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>
        
        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6">
          {/* Stats Cards */}
          <div className="grid grid-cols-4 gap-4 mb-6">
            <div className="bg-red-50 rounded-xl p-4 text-center">
              <AlertTriangle className="w-8 h-8 text-red-500 mx-auto mb-2" />
              <p className="text-2xl font-bold text-red-700">{totalErrors}</p>
              <p className="text-xs text-red-600">Total Errors</p>
            </div>
            <div className="bg-green-50 rounded-xl p-4 text-center">
              <CheckCircle2 className="w-8 h-8 text-green-500 mx-auto mb-2" />
              <p className="text-2xl font-bold text-green-700">{correctedCount}</p>
              <p className="text-xs text-green-600">Corrected</p>
            </div>
            <div className="bg-slate-50 rounded-xl p-4 text-center">
              <XCircle className="w-8 h-8 text-slate-500 mx-auto mb-2" />
              <p className="text-2xl font-bold text-slate-700">{ignoredCount}</p>
              <p className="text-xs text-slate-600">Ignored</p>
            </div>
            <div className="bg-amber-50 rounded-xl p-4 text-center">
              <TrendingUp className="w-8 h-8 text-amber-500 mx-auto mb-2" />
              <p className="text-2xl font-bold text-amber-700">
                {totalErrors > 0 ? Math.round((correctedCount / totalErrors) * 100) : 0}%
              </p>
              <p className="text-xs text-amber-600">Correction Rate</p>
            </div>
          </div>
          
          {/* Pattern Distribution */}
          <div className="mb-6">
            <h3 className="text-sm font-semibold text-slate-700 mb-3 flex items-center gap-2">
              <PieChart className="w-4 h-4" />
              Pattern Distribution
            </h3>
            <div className="space-y-3">
              {patternPercentages.map(({ pattern, count, percentage, color }) => (
                <div key={pattern}>
                  <div className="flex items-center justify-between text-sm mb-1">
                    <span className="text-slate-700">{pattern}</span>
                    <span className="text-slate-500">{count} ({percentage}%)</span>
                  </div>
                  <div className="h-2 bg-slate-100 rounded-full overflow-hidden">
                    <div 
                      className="h-full rounded-full transition-all duration-500"
                      style={{ width: `${percentage}%`, backgroundColor: color }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>
          
          {/* Error Table */}
          <div className="mb-6">
            <h3 className="text-sm font-semibold text-slate-700 mb-3 flex items-center gap-2">
              <FileText className="w-4 h-4" />
              Error Details
            </h3>
            <div className="border border-slate-200 rounded-xl overflow-hidden">
              <table className="w-full text-sm">
                <thead className="bg-slate-50">
                  <tr>
                    <th className="px-4 py-2 text-left text-slate-600 font-medium">Original</th>
                    <th className="px-4 py-2 text-left text-slate-600 font-medium">Correction</th>
                    <th className="px-4 py-2 text-left text-slate-600 font-medium">Pattern</th>
                    <th className="px-4 py-2 text-left text-slate-600 font-medium">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {errorTokens.map((token) => (
                    <tr key={token.id} className="hover:bg-slate-50">
                      <td className="px-4 py-2 sinhala-text text-red-700">{token.originalWord}</td>
                      <td className="px-4 py-2 sinhala-text text-green-700">{token.correctedWord}</td>
                      <td className="px-4 py-2 text-slate-600 text-xs">{token.pattern}</td>
                      <td className="px-4 py-2">
                        <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${
                          token.state === 'corrected' 
                            ? 'bg-green-100 text-green-700' 
                            : token.state === 'ignored'
                            ? 'bg-slate-100 text-slate-600'
                            : 'bg-amber-100 text-amber-700'
                        }`}>
                          {token.state}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
          
          {/* Text Comparison */}
          <div>
            <h3 className="text-sm font-semibold text-slate-700 mb-3 flex items-center gap-2">
              <FileText className="w-4 h-4" />
              Text Comparison
            </h3>
            <div className="grid grid-cols-2 gap-4">
              <div className="p-4 bg-red-50 rounded-xl border border-red-100">
                <p className="text-xs text-red-600 font-medium mb-2">Original</p>
                <p className="sinhala-text text-red-800">{originalText}</p>
              </div>
              <div className="p-4 bg-green-50 rounded-xl border border-green-100">
                <p className="text-xs text-green-600 font-medium mb-2">Corrected</p>
                <p className="sinhala-text text-green-800">{getFinalText()}</p>
              </div>
            </div>
          </div>
        </div>
        
        {/* Footer */}
        <div className="px-6 py-4 bg-slate-50 border-t border-slate-100 flex items-center justify-between">
          <div className="text-xs text-slate-500">
            Model: {modelUsed} • Processing: {processingTime?.toFixed(0)}ms
          </div>
          <button
            onClick={handleExport}
            className="flex items-center gap-2 px-4 py-2 bg-indigo-500 text-white rounded-lg text-sm font-medium hover:bg-indigo-600 transition-colors"
          >
            <Download className="w-4 h-4" />
            Export Report
          </button>
        </div>
      </div>
    </div>
  );
}

export default ReportModal;
